Fixed html formatting to raw in grid columns
hiqdev/hipanel-module-ipam pull request #7
Opened 2021-05-07 12:19 UTC by strorch

2021-05-07 19:54 UTC, hiqsol requested changes

2021-05-07 19:54 UTC, hiqsol commented on src/grid/PrefixGridView.php
> +                    if ($prefix->isSuggersted()) {
typo

2021-05-11 12:02 UTC, SilverFire approved these changes

2021-05-18 15:38 UTC, hiqsol approved these changes

2021-05-18 15:39 UTC, merged